module JsonSpotter
  class Selection
    include Enumerable[Hash[_ToS, any]]

    interface _SelectionStream
      def read: () -> String
    end

    interface _Query
      def match?: (untyped) -> untyped
    end

    @query: _Query
    @stream: _SelectionStream

    def initialize: (_SelectionStream, query: _Query) -> void
  end
end
